export const ACCOMMODATION = {
    TH: {
        ACCOMMODATION: {
            TITLE: 'ที่พักชุมชน',
        },
        ARRANGEMENT: 'การจัดเรียง',
        HIGHLIGHT: 'ไฮไลท์',
        LATEST: 'อัปเดตล่าสุด',
        SEARCH: 'ค้นหา',
        RESULT: 'ผลการค้นหา',
        NO_DATA: 'ไม่พบข้อมูล',
        PROVINCE: 'จังหวัด',
        COMMUNITY: 'ชุมชน',
        KEYWORD: 'คำค้นหา',
        CONTENT: {
            ACCOMMODATION_DETAIL: 'รายละเอียดที่พัก',
            GROUP_SIZE: 'จำนวนคนที่รองรับ',
            PERSON: 'คน',
            FEE: 'ค่าบริการ',
            BATH_PER_PERSON: 'บาท/คน',
            FACILITIES: 'สิ่งอำนวยความสะดวก',
            CONTACTS: 'ข้อมูลการติดต่อ',
            TEL: 'โทร',
            TRAINING_COURSE: 'หลักสูตรการอบรม',
            WEBSITE: 'เว็บไซต์',
            TAT_REGISTER: 'หมายเลขไอดีที่จดทะเบียน',
            ADDRESS: 'ที่อยู่',
            TAG: 'แท็กที่เกี่ยวข้อง',
        },
    },
    EN: {
        ACCOMMODATION: {
            TITLE: 'Accommodations',
        },
        ARRANGEMENT: 'Sort by',
        HIGHLIGHT: 'Highlight',
        LATEST: 'Latest',
        SEARCH: 'Search',
        RESULT: 'Result',
        NO_DATA: 'No data',
        PROVINCE: 'Province',
        COMMUNITY: 'Community',
        KEYWORD: 'Keyword',
        CONTENT: {
            ACCOMMODATION_DETAIL: 'Accomodation details',
            GROUP_SIZE: 'Total accommodate',
            PERSON: 'people',
            FEE: 'Price',
            BATH_PER_PERSON: 'Baht/Person',
            FACILITIES: 'Facilities',
            CONTACTS: 'Contact information',
            TEL: 'Tel.',
            TRAINING_COURSE: 'Trained courses',
            WEBSITE: 'Website',
            TAT_REGISTER: 'Registered ID',
            ADDRESS: 'Address',
            TAG: 'Related Tags',
        },
    },
}
