export const ATTRACTION = {
    TH: {
        ATTRACTION: {
            HEADER: 'สถานที่ท่องเที่ยว/กิจกรรมน่าสนใจ',
            TITLE: 'สถานที่ท่องเที่ยว/กิจกรรมทั้งหมด',
        },
        ARRANGEMENT: 'การจัดเรียง',
        HIGHLIGHT: 'ไฮไลท์',
        LATEST: 'อัปเดตล่าสุด',
        SEARCH: 'ค้นหา',
        RESULT: 'ผลการค้นหา',
        NO_DATA: 'ไม่พบข้อมูล',
        CULTURAL_ACTIVITY: 'ประเภทกิจกรรม',
        PROVINCE: 'จังหวัด',
        COMMUNITY: 'ชุมชน',
        KEYWORD: 'คำค้นหา',
        CONTENT: {
            ATTRACTION_DETAIL: 'รายละเอียดกิจกรรม',
            FACILITIES: 'สิ่งอำนวยความสะดวก',
            MONTH_PERIOD: 'ช่วงเวลาที่เหมาะสม',
            ALL_SEASON: 'ตลอดทั้งปี',
            TRAVELING: 'การเดินทาง',
            PRIVATE_TRANSITION: 'การเดินทางด้วยรถส่วนตัว',
            PUBLIC_TRANSITION: 'การเดินทางด้วยรถสาธารณะ',
            OPEN_DAY: 'วัน-เวลาทำการ',
            LANDMARK: 'จุดสังเกต',
            FEE: 'ค่าใช้จ่ายในกิจกรรม',
            ATTRACTION_PEIOD: 'ระยะเวลาทำกิจกรรม',
            CONTACTS: 'ข้อมูลการติดต่อ',
            TEL: 'โทร',
            WEBSITE: 'เว็บไซต์',
            ADDRESS: 'ที่อยู่',
            TAG: 'แท็กที่เกี่ยวข้อง',
            MINUTE: 'นาที',
            BAHTPERPERSON: 'บาท/คน',
        },
    },
    EN: {
        ATTRACTION: {
            HEADER: 'Interesting attractions/activities',
            TITLE: 'All Attractions/Activities',
        },
        ARRANGEMENT: 'Sort by',
        HIGHLIGHT: 'Highlight',
        LATEST: 'Latest',
        SEARCH: 'Search',
        RESULT: 'Results',
        NO_DATA: 'No Data',
        CULTURAL_ACTIVITY: 'activities type',
        PROVINCE: 'Province',
        COMMUNITY: 'Community',
        KEYWORD: 'Keyword',
        CONTENT: {
            ATTRACTION_DETAIL: 'Activity details',
            FACILITIES: 'Facilities',
            MONTH_PERIOD: 'Appropriate season for travel',
            ALL_SEASON: 'All Season',
            TRAVELING: 'Traveling',
            PRIVATE_TRANSITION: 'Traveling by private car',
            PUBLIC_TRANSITION: 'Traveling by public transport',
            OPEN_DAY: 'Office hours',
            LANDMARK: 'Landmark',
            FEE: 'The cost of activities ',
            ATTRACTION_PEIOD: 'Activity duration',
            CONTACTS: 'Contacts',
            TEL: 'Tel.',
            WEBSITE: 'Website',
            ADDRESS: 'Address',
            TAG: 'Related Tags',
            MINUTE: 'Minutes',
            BAHTPERPERSON: 'baht/person',
        },
    },
}
