export const COMMUNITY = {
    TH: {
        TITLE: 'รีวิวท่องเที่ยวโดยชุมชน',
        ARRANGEMENT: 'การจัดเรียง',
        HIGHLIGHT: 'ไฮไลท์',
        LATEST: 'อัปเดตล่าสุด',
        CONTENT: {
            TRAVEL_LINK: 'แหล่งท่องเที่ยวเชื่อมโยง (ระยะห่างจากชุมชน)',
            COORDINATES: 'พิกัด',
            KILOMETER: 'กม.',
            COORDINATES_TRAVEL: 'พิกัดการเดินทางไปยังชุมชน',
            JOURNEY: 'การเดินทาง',
            PRIVATE_TRAVEL: 'สำหรับผู้เดินทางโดยรถยนต์ส่วนตัว',
            PUBLIC_TRAVEL: 'สำหรับผู้เดินทางโดยรถสาธารณะ',
            PUBLIC_TRAVEL_AIR: 'สำหรับผู้เดินทางโดยเครื่องบิน',
            CONTACT: 'ติดต่อผู้ประสานงานการท่องเที่ยวโดยชุมชน และที่พักโฮมสเตย์ได้ที่',
            TEL: 'โทร.',
            FACEBOOK: 'Facebook Page',
            TAG: 'แท็กที่เกี่ยวข้อง',
        },
    },
    EN: {
        TITLE: 'Community Review',
        ARRANGEMENT: 'Sort by',
        HIGHLIGHT: 'Highlight',
        LATEST: 'Latest',
        CONTENT: {
            TRAVEL_LINK: 'Travel links (Distance from the community)',
            COORDINATES: 'Coordinates',
            KILOMETER: 'km',
            COORDINATES_TRAVEL: 'Coordinates travel to the community',
            JOURNEY: 'The journey',
            PRIVATE_TRAVEL: 'For those traveling by private car,',
            PUBLIC_TRAVEL: 'For those traveling by public transportation,',
            PUBLIC_TRAVEL_AIR: 'For those traveling by plane,',
            CONTACT: 'Contact community-based tourism and homestay accommodation at',
            TEL: 'Tel.',
            FACEBOOK: 'Facebook Page',
            TAG: 'SEO KEYWORD',
        },
    },
}
