export const PROFILE = {
    TH: {
        PROFILE: 'ข้อมูลส่วนตัว',
        YOUR_INTEREST: 'สิ่งที่คุณสนใจ',
        EDIT_PROFILE: 'แก้ไขข้อมูลส่วนตัว',
        MY_TRIP: 'ทริปของฉัน',
        CREATE_TRIP: 'สร้างทริป',
        CREATE_NEW_TRIP: 'สร้างทริปใหม่',
        CONFIRM_DELETE: 'คุณต้องการลบทริปของฉันหรือไม่',
        INTERESTED: 'สิ่งที่คุณสนใจ',
        ERROR_SYSTEM_MAIN_TEXT: 'ระบบเกิดข้อผิดพลาด',
        ERROR_SYSTEM_MINOR_TEXT: 'กรุณาติดต่อเจ้าหน้าที่',

        USER_DISABLED_MAIN_TEXT: 'แจ้งเตือนจากระบบ',
        USER_DISABLED_TEXT: 'บัญชีนี้ได้ปิดการใช้งาน กรุณาติดต่อเจ้าหน้าที่',

        USER_NOT_VERIFY_EMAIL_MAIN_TEXT: 'บัญชีนี้ยังไม่ได้ยืนยันตัวตน',
        USER_NOT_VERIFY_EMAIL_MINOR_TEXT: 'บัญชีนี้ยังไม่ได้ยืนยันตัวตนในที่อยู่อีเมล กรุณาตรวจสอบที่อยู่อีเมล',
        USER_NOT_FOUND_EMAIL_MAIN_TEXT: 'ไม่พบอีเมลนี้ในระบบ',
        USER_NOT_FOUND_EMAIL_MINOR_TEXT: 'คุณยังไม่ได้เป็นสมาชิก กรุณาสมัครสมาชิกและยืนยันตัวตน จึงจะสามารถเปลี่ยนรหัสผ่านได้',
        USER_FORGOT_PASSWORD_MAIN_TEXT: 'ส่งคำร้องขอเปลี่ยนรหัสผ่านสำเร็จ',
        USER_FORGOT_PASSWORD_MINOR_TEXT: 'ระบบได้ส่งข้อมูลสำหรับใช้เปลี่ยนรหัสผ่านไปยังอีเมลของคุณแล้ว กรุณาตรวจสอบอีเมลเพื่อเปลี่ยนรหัสผ่าน',
        USER_EXIST_EMAIL_MAIN_TEXT: 'อีเมลนี้มีอยู่ในระบบอยู่แล้ว',
        USER_EXIST_EMAIL_MINOR_TEXT: 'หากต้องการสมัครสมาชิก สามารถเปลี่ยนอีเมลที่ไม่มีอยู่ในระบบได้',
        USER_REGISTER_SUCCESS_MAIN_TEXT: 'ลงทะเบียนสำเร็จ',
        USER_REGISTER_SUCCESS_MINOR_TEXT: 'ระบบได้ส่งข้อมูลสำหรับใช้ยืนยันตัวตนไปยังอีเมลของคุณแล้ว กรุณาตรวจสอบอีเมลเพื่อเปิดใช้งานบัญชีและเข้าสู่ระบบ',

        ERROR_LOGIN_FACEBOOK_TEXT: 'ไม่สามารถเข้าสู่ระบบด้วย facebook กรุณาติดต่อเจ้าหน้าที่',
        ERROR_LOGIN_GOOGLE_TEXT: 'ไม่สามารถเข้าสู่ระบบด้วย google กรุณาติดต่อเจ้าหน้าที่',
        WHAT_IS_YOUR_INTERESTED: 'สิ่งที่คุณกำลังสนใจ ?',
        INTERESTED_DESC: 'เพื่อพัฒนาประสบการณ์การใช้งานเว็บของคุณให้ดียิ่งขึ้น บอกเราสักนิดถึงสิ่งที่คุณกำลังสนใจ',
        DEACTIVATE_ACCOUNT: 'ปิดการใช้งานบัญชี',
        CONFIRM_CLOSE_ACCOUNT_MAIN_TEXT: 'ปิดการใช้งานบัญชี',
        CONFIRM_CLOSE_ACCOUNT_MINOR_TEXT:
            'บัญชีของคุณจะถูกระงับการใช้งาน คุณสามารถกู้คืนบัญชีได้โดยการลงชื่อเข้าสู่ระบบภายใน 90 วัน',
        // CONFIRM_CLOSE_ACCOUNT_MINOR_TEXT:
        //     'บัญชีของคุณจะถูกระงับการใช้งาน หากต้องการกู้คืนบัญชีกรุณาติดต่อเจ้าหน้าที่ผ่านทาง contact@dasta.or.th ภายใน 90 วัน',
        BTN_CONFIRM_TEXT: 'ปิดการใช้งาน',
        BTN_CANCEL_TEXT: 'ยกเลิก',
        CONFIRM_EDIT: 'คุณต้องการแก้ไขข้อมูลส่วนตัว หรือไม่',
        BTN_SAVE: 'บันทึก',
        BTN_CONFIRM: 'ยืนยัน',
        SUBMIT: 'ตกลง',
        OK_TEXT: 'ตกลง',
        ERROR_UPLOAD_FILE_TO_TEMP_MAIN_TEXT: 'ไม่สามารถสามารถอัปโหลดได้',
        ERROR_UPLOAD_FILE_TO_TEMP_TYPE_MINOR_TEXT: 'คุณสามารถอัปโหลดนามสกุลไฟล์ JPG/PNG ได้เท่านั้น',
        ERROR_UPLOAD_FILE_TO_TEMP_SIZE_MINOR_TEXT: 'รูปภาพต้องมีขนาดไม่เกิน 5 MB',
    },
    EN: {
        PROFILE: 'Profile',
        YOUR_INTEREST: 'Your interest',
        EDIT_PROFILE: 'Edit Profile',
        MY_TRIP: 'My Trip',
        CREATE_TRIP: 'Create Trip',
        CREATE_NEW_TRIP: 'Create New Trip',
        CONFIRM_DELETE: 'Are you sure you want to remove my trip?',
        INTERESTED: 'Interested',

        USER_DISABLED_MAIN_TEXT: 'System',
        USER_DISABLED_TEXT: 'This account is disabled, please contact staff.',

        USER_NOT_VERIFY_EMAIL_MAIN_TEXT: 'Your account is not verify',
        USER_NOT_VERIFY_EMAIL_MINOR_TEXT: 'This account is not verify email account, please check your email account.',
        USER_NOT_FOUND_EMAIL_MAIN_TEXT: 'Your account is not exist',
        USER_NOT_FOUND_EMAIL_MINOR_TEXT: 'This account not found, please register your for log in.',
        USER_FORGOT_PASSWORD_MAIN_TEXT: 'Your change password request is sent',
        USER_FORGOT_PASSWORD_MINOR_TEXT: 'Please check your email account for change to new password.',
        USER_EXIST_EMAIL_MAIN_TEXT: 'Your account is already exist',
        USER_EXIST_EMAIL_MINOR_TEXT: 'Please register with new email account, if you want to register again.',
        USER_REGISTER_SUCCESS_MAIN_TEXT: 'Your registration success',
        USER_REGISTER_SUCCESS_MINOR_TEXT: 'Please verify or activate your email account for log in.',

        ERROR_SYSTEM_MAIN_TEXT: 'System error',
        ERROR_SYSTEM_MINOR_TEXT: 'Please contact staff.',

        ERROR_LOGIN_FACEBOOK_TEXT: "Can't log in with facebook, please contact staff.",
        ERROR_LOGIN_GOOGLE_TEXT: "Can't log in with google please contact staff.",
        WHAT_IS_YOUR_INTERESTED: 'What is your interested?',
        INTERESTED_DESC: 'To improve a better experience for you. Please tell us about your interest.',
        DEACTIVATE_ACCOUNT: 'Account deactivation',
        CONFIRM_CLOSE_ACCOUNT_MAIN_TEXT: 'Account deactivation',
        CONFIRM_CLOSE_ACCOUNT_MINOR_TEXT:
            'Your account will be deactivated. You can recover your account by log in within 90 days.',
        // CONFIRM_CLOSE_ACCOUNT_MINOR_TEXT:
        // 'Your account will be deactivated. If you want to recover your account, please contact us through contact@dasta.or.th within 90 days.',
        BTN_CONFIRM_TEXT: 'Disabled',
        BTN_CANCEL_TEXT: 'Cancel',
        CONFIRM_EDIT: 'Would you like to edit your personal information?',
        BTN_SAVE: 'Save',
        BTN_CONFIRM: 'Submit',
        SUBMIT: 'Confirm',
        ERROR_UPLOAD_FILE_TO_TEMP_MAIN_TEXT: "Can't upload",
        ERROR_UPLOAD_FILE_TO_TEMP_TYPE_MINOR_TEXT: 'You can only upload JPG / PNG file extension.',
        ERROR_UPLOAD_FILE_TO_TEMP_SIZE_MINOR_TEXT: 'Images cannot be larger than 5 MB.',
        OK_TEXT: 'OK',
    },
}
