export const SEASON = {
    TH: {
        SEASON: {
            TITLE: 'ท่องเที่ยวชุมชนตามฤดู',
        },
        SEE_ALL: 'ดูทั้งหมด',
        SEARCH: 'ค้นหา',
        RESULT: 'ผลการค้นหา',
        NO_DATA: 'ไม่พบข้อมูล',
        PROVINCE: 'จังหวัด',
        MONTH: 'เดือน',
        COMMUNITY: 'ชุมชน',
        KEYWORD: 'คำค้นหา',
        ARRANGEMENT: 'การจัดเรียง',
        HIGHLIGHT: 'ไฮไลท์',
        LATEST: 'อัปเดตล่าสุด',
        CONTENT: {
            WAY_OF_LIFE: 'ด้านวิถีชีวิต',
            LIFESTYLE: 'วิถีชีวิต',
            ART: 'ศิลปะ',
            LANGUAGE: 'ภาษา',
            DRESS: 'การแต่งกาย',
            TRADITION: 'ประเพณี',
            FOOD: 'อาหาร',
            SOUVENIR: 'ของฝาก / ของที่ระลึก',
            POINT: 'ความโดดเด่น',
            TOURIST_CONDUCT: 'ข้อปฏิบัติของนักท่องเที่ยว',
            ACTIVITIES: 'กิจกรรมการท่องเที่ยวเชิงสร้างสรรค์',
            ATTRACTION: 'แหล่งท่องเที่ยวเชื่อมโยง',
            ATTRACTION_IN_COMMUNITY: 'ดูสถานที่ท่องเที่ยว/กิจกรรมภายในชุมชน',
            FACILITIES: 'สิ่งอำนวยความสะดวก',
            PAYMENT: 'ช่องทางการชำระเงิน',
            LOCAL_GUIDE_EXIST: 'นักเล่าเรื่อง',
            GUIDE: 'ไกด์นำเที่ยว',
            TRAVELING: 'การเดินทาง',
            PRIVATE_TRANSITION: 'การเดินทางด้วยรถส่วนตัว',
            PUBLIC_TRANSITION: 'การเดินทางด้วยรถสาธารณะ',
            INFORMATION: 'ข้อมูลการท่องเที่ยว',
            DATE_TIME: 'วัน-เวลาทำการ',
            TOURIST_GROUP: 'กลุ่มนักท่องเที่ยวที่รองรับ',
            HIGH_SEASON: 'ช่วงเวลาที่เหมาะสมในการท่องเที่ยว',
            ALL_SEASON: 'ตลอดทั้งปี',
            ACCOMMODATION_TYPE: 'ประเภทที่พัก',
            CONTACT: 'ข้อมูลการติดต่อ',
            CONTACT_NAME: 'ชื่อ',
            CONTACT_TEL: 'โทร',
            CONTACT_POSITION: 'ตำแหน่ง',
            CONTACT_LINE: 'Line',
            CONTACT_FACEBOOK: 'Facebook',
            CONTACT_EMAIL: 'E-mail',
            COMMUNITY_CONTACT: 'ผู้ติดต่อของชุมชน',
            COMMUNITY_DETAIL: 'รายละเอียดชุมชน',
            YEAR_OF_OPERATION: 'ปีที่ลงไปดำเนินการ',
            YEAR_OF_GROUP_ESTABLISHMENT: 'ปีที่ก่อตั้ง',
            YEAR_OF_ESTABLISHMENT: 'จำนวนปีที่ตั้ง',
            MENTOR_UNIT: 'หน่วยงานพี่เลี้ยง',
            TOURISM_STANDARD: 'มาตรฐานการท่องเที่ยวปลอดภัย',
            PRIZE_STANDARD: 'รางวัลและมาตรฐาน',
            REMARK: 'หมายเหตุ',
            TAG: 'แท็กที่เกี่ยวข้อง',
            ATTRACTION_LEGEND: 'กิจกรรม',
            RELATTRACTION_LEGEND: 'แหล่งท่องเที่ยวเชื่อมโยง',
        },
        ATTRACTION: {
            TITLE: 'สถานที่ท่องเที่ยว / กิจกรรมภายใน',
        },
    },
    EN: {
        SEASON: {
            TITLE: 'Season Travel',
        },
        SEE_ALL: 'View All',
        SEARCH: 'Search',
        RESULT: 'Results',
        NO_DATA: 'No Data',
        PROVINCE: 'Province',
        MONTH: 'Month',
        COMMUNITY: 'Community',
        KEYWORD: 'Keyword',
        ARRANGEMENT: 'Sort by',
        HIGHLIGHT: 'Highlight',
        LATEST: 'Latest',
        CONTENT: {
            WAY_OF_LIFE: 'Community lifestyle',
            LIFESTYLE: 'Lifestyle',
            SOUVENIR: 'Souvenir',
            ART: 'Cultural arts',
            LANGUAGE: 'Language',
            DRESS: 'Uniqueness dressing',
            TRADITION: 'Tradition',
            FOOD: 'Food',
            POINT: 'Community uniqueness',
            TOURIST_CONDUCT: 'Community rules',
            ACTIVITIES: 'Tourism activities',
            ATTRACTION: 'Nearby tourist attractions',
            ATTRACTION_IN_COMMUNITY: 'View community attractions/activities',
            FACILITIES: 'Facilities',
            PAYMENT: 'Payment',
            LOCAL_GUIDE_EXIST: 'Storyteller',
            GUIDE: 'Guide',
            TRAVELING: 'The journey',
            PRIVATE_TRANSITION: 'Traveling by private car',
            PUBLIC_TRANSITION: 'Traveling by public transport',
            INFORMATION: 'Tourist information',
            DATE_TIME: 'Office hours',
            TOURIST_GROUP: 'Tourist group supported',
            HIGH_SEASON: 'Appropriate season for travel',
            ALL_SEASON: 'All Season',
            ACCOMMODATION_TYPE: 'Accommodation type',
            CONTACT: 'Contact information',
            CONTACT_NAME: 'Contact person',
            CONTACT_TEL: 'Tel.',
            CONTACT_POSITION: 'Position',
            CONTACT_LINE: 'Line',
            CONTACT_FACEBOOK: 'Facebook',
            CONTACT_EMAIL: 'E-mail',
            COMMUNITY_CONTACT: 'Community contact',
            COMMUNITY_DETAIL: 'Community details',
            YEAR_OF_OPERATION: 'Year of Survey',
            YEAR_OF_GROUP_ESTABLISHMENT: 'Year of Group Establishment',
            YEAR_OF_ESTABLISHMENT: 'Number of years establishment',
            MENTOR_UNIT: 'Supporter',
            TOURISM_STANDARD: 'Safety & Health Administration',
            PRIZE: 'Award',
            REMARK: 'Remark',
            TAG: 'Related Tags',
            ATTRACTION_LEGEND: 'Activities',
            RELATTRACTION_LEGEND: 'Relation Attraction',
        },
        ATTRACTION: {
            TITLE: 'Community attractions/activities',
        },
    },
}
