export const TRIP = {
    TH: {
        // ปุ่ม
        BTN_OK_TEXT: 'ตกลง',
        BTN_CONFIRM_TEXT: 'ยืนยัน',
        BTN_CANCEL_TEXT: 'ยกเลิก',
        BTN_ADD_LOCATION_TEXT: 'เพิ่มสถานที่',
        BTN_EDIT_LOCATION_TEXT: 'เพิ่ม / แก้ไข สถานที่',
        BTN_SEARCH_TEXT: 'ค้นหา',
        BTN_ADD_TRIP_TEXT: 'สร้างทริป',
        BTN_EDIT_TRIP_TEXT: 'แก้ไขทริป',
        BTN_DELETE_TEXT: 'ลบ',
        // หัวข้อ
        BUDGET_TEXT: 'งบประมาณค่าใช้จ่าย (บาท)',
        TOTAL_COST_TEXT: 'ค่าใช้จ่ายรวมโดยประมาณ (บาท)',
        TOTAL_COST_TEXT_TWO: 'ค่าใช้จ่ายรวมโดยประมาณ',
        TOTAL_COST_DAILY_TEXT: 'ค่าใช้จ่ายรายวัน',
        SEARCH_RESULT_TEXT: 'ผลการค้นหา',
        ACTIVITY_DURATION_TEXT: 'ระยะเวลาในการทำกิจกรรม',
        ESTIMATE_COST_TEXT: 'ค่าใช้จ่ายโดยประมาณ',
        ESTIMATE_COST_OVER_TEXT: 'คุณมีค่าใช้จ่ายในการทำกิจกรรมเกินกว่างบประมาณที่ตั้งใว้',
        SELECT_TEXT: 'เลือก',
        CREATE_NEW_TRIP_TEXT: 'สร้างทริปใหม่',
        UPDATE_TRIP_TEXT: 'แก้ไขทริปของฉัน',
        NAME_YOUR_TRIP_TEXT: 'ชื่อทริปของคุณ',
        COUNT_DAYS_TEXT: 'จำนวนวัน',
        SELECTED_LOCATION_TEXT: 'สถานที่ที่ถูกเลือก',
        MY_TRIP_TEXT: 'ทริปของฉัน',

        // หน่วย
        UNIT_KM_TEXT: 'กม.',
        UNIT_BATH_TEXT: 'บาท',
        UNIT_MINUTE_TEXT: 'นาที',
        UNIT_DAY_TEXT: 'วันที่ [{day}]',

        // ข้อความ dialog
        CONFIRM_DELETE_TRIP_MAIN_TEXT: 'ลบทริปของฉัน',
        CONFIRM_DELETE_TRIP_MINOR_TEXT: 'คุณต้องการลบ "[{tripName}]" หรือไม่',
        CONFIRM_CANCEL_TRIP_MAIN_TEXT: 'การเปลี่ยนแปลงของคุณ ยังไม่ถูกบันทึก',
        CONFIRM_CANCEL_TRIP_MINOR_TEXT: 'ต้องการออกจากหน้านี้หรือไม่',
        NOT_SELECTED_LOCATION_MAIN_TEXT: 'คุณยังไม่ได้เลือกสถานที่สำหรับทริปในวันที่ [{days}]',
        NOT_SELECTED_LOCATION_MINOR_TEXT: 'หากคุณไม่ต้องการเพิ่มสถานที่ สามารถกดปุ่มลบวันได้',
        LIMIT_SELECTED_LOCATION_MAIN_TEXT: 'คุณสามารถเลือกสถานที่ได้สูงสุดจำนวน 10 สถานที่',
        LIMIT_SELECTED_LOCATION_MINOR_TEXT:
            'หากคุณต้องการเลือกสถานที่ ให้เลือกสถานที่ไม่ต้องการออกจากรายการที่ถูกเลือก',
        CONFIRM_DELETE_DAY_MAIN_TEXT: 'ลบวัน',
        CONFIRM_DELETE_DAY_MINOR_TEXT: 'คุณต้องการลบ Day [{day}] หรือไม่ ?',
        SUCCESS_CREATE_NEW_TRIP_MAIN_TEXT: 'สร้างทริปใหม่สำเร็จ',
        SUCCESS_CREATE_NEW_TRIP_MINOR_TEXT: 'ชื่อทริปของคุณ คือ  [{tripName}]',
        SUCCESS_UPDATE_TRIP_MAIN_TEXT: 'แก้ไขทริปของฉันสำเร็จ',
        SUCCESS_UPDATE_TRIP_MINOR_TEXT: 'ชื่อทริปของคุณ คือ [{tripName}]',
        ERROR_SYSTEM_MAIN_TEXT: 'ระบบเกิดข้อผิดพลาด',
        ERROR_SYSTEM_MINOR_TEXT: 'กรุณาลองใหม่อีกครั้ง',
        SUCCESS_REMOVE_TRIP_MAIN_TEXT: 'ลบทริปของฉันสำเร็จ',
        SUCCESS_REMOVE_TRIP_MINOR_TEXT: 'ชื่อทริปที่ถูกลบ คือ [{tripName}]',
        LIMIT_NEW_DAY_MAIN_TEXT: 'คุณสามารถเพิ่มวันได้สูงสุดจำนวน 5 วัน',
        LIMIT_NEW_DAY_MINOR_TEXT: 'หากคุณต้องการเพิ่มวัน ให้ลบวันที่ไม่ต้องการออก',
        REMOVE_LOCATION_MAIN_TEXT: 'ลบสถานที่',
        REMOVE_LOCATION_MINOR_TEXT: 'คุณต้องการลบสถานที่นี้หรือไม่?',
        ERROR_CREATE_NEW_TRIP_MAIN_TEXT: 'ไม่สามารถสร้างทริปนี้ได้ คุณมีจำนวนทริปเกิน 10 ทริป',
        ERROR_CREATE_NEW_TRIP_MINOR_TEXT: 'หากคุณต้องการสร้างทริปเพิ่ม สามารถลบทริปที่ไม่ต้องการได้',

        // validate,
        PLEASE_SELECT_TEXT: 'กรุณาเลือกจังหวัด',
        PLEASE_ENTER_TEXT: 'กรุณากรอกชื่อทริป',
    },
    EN: {
        // ปุ่ม
        BTN_OK_TEXT: 'OK',
        BTN_CONFIRM_TEXT: 'Remove',
        BTN_CANCEL_TEXT: 'Cancel',
        BTN_ADD_LOCATION_TEXT: 'Add Location',
        BTN_EDIT_LOCATION_TEXT: 'Add / Edit Location',
        BTN_SEARCH_TEXT: 'Search',
        BTN_ADD_TRIP_TEXT: 'Create Trip',
        BTN_EDIT_TRIP_TEXT: 'Edit Trip',
        BTN_DELETE_TEXT: 'Remove',

        // หัวข้อ
        BUDGET_TEXT: 'Trip budget (Baht)',
        TOTAL_COST_TEXT: 'Total estimated cost (Baht)',
        TOTAL_COST_TEXT_TWO: 'Total estimated cost',
        TOTAL_COST_DAILY_TEXT: 'Daily cost',
        SEARCH_RESULT_TEXT: 'Search Result',
        ACTIVITY_DURATION_TEXT: 'Activity duration',
        ESTIMATE_COST_TEXT: 'Estimated cost',
        ESTIMATE_COST_OVER_TEXT: 'The estimated cost is over your budget.',
        SELECT_TEXT: 'Select',
        CREATE_NEW_TRIP_TEXT: 'Create a new trip',
        UPDATE_TRIP_TEXT: 'Edit my trip',
        NAME_YOUR_TRIP_TEXT: 'The name of your trip',
        COUNT_DAYS_TEXT: 'Number of days',
        SELECTED_LOCATION_TEXT: 'Selected location',
        MY_TRIP_TEXT: 'My Trip',

        // หน่วย
        UNIT_KM_TEXT: 'km.',
        UNIT_BATH_TEXT: 'baht.',
        UNIT_MINUTE_TEXT: 'minute',
        UNIT_DAY_TEXT: 'Day [{day}]',
        // ข้อความ dialog
        CONFIRM_DELETE_TRIP_MAIN_TEXT: 'Remove My Trip',
        CONFIRM_DELETE_TRIP_MINOR_TEXT: 'Do you want to remove "[{tripName}]"',
        CONFIRM_CANCEL_TRIP_MAIN_TEXT: 'Change of you Not recorded yet',
        CONFIRM_CANCEL_TRIP_MINOR_TEXT: 'Want to leave this page?',
        NOT_SELECTED_LOCATION_MAIN_TEXT: "You haven't selected a destination for the trip on [{days}]",
        NOT_SELECTED_LOCATION_MINOR_TEXT: "If you don't want to add a place Can press the button to delete the day",
        LIMIT_SELECTED_LOCATION_MAIN_TEXT: 'You can select a maximum of 10 locations.',
        LIMIT_SELECTED_LOCATION_MINOR_TEXT:
            "If you want to choose the location Select the place you don't want from the selected list.",
        CONFIRM_DELETE_DAY_MAIN_TEXT: 'Remove Day',
        CONFIRM_DELETE_DAY_MINOR_TEXT: 'Do you want to remove Day [{day}]?',
        SUCCESS_CREATE_NEW_TRIP_MAIN_TEXT: 'Create trip successfully',
        SUCCESS_CREATE_NEW_TRIP_MINOR_TEXT: 'The name of your trip is [{tripName}].',
        SUCCESS_UPDATE_TRIP_MAIN_TEXT: 'Edit trip successfully',
        SUCCESS_UPDATE_TRIP_MINOR_TEXT: 'You can see [{tripName}] details on your profile.',
        ERROR_SYSTEM_MAIN_TEXT: 'Something went wrong',
        ERROR_SYSTEM_MINOR_TEXT: 'Please try again.',
        SUCCESS_REMOVE_TRIP_MAIN_TEXT: 'Remove trip successfully',
        SUCCESS_REMOVE_TRIP_MINOR_TEXT: '[{tripName}] already remove from my trip',
        LIMIT_NEW_DAY_MAIN_TEXT: 'You can add a maximum of 5 days.',
        LIMIT_NEW_DAY_MINOR_TEXT: 'If you want to add more days Delete any unwanted days.',
        REMOVE_LOCATION_MAIN_TEXT: 'Remove location',
        REMOVE_LOCATION_MINOR_TEXT: 'Do you want to remove location?',
        ERROR_CREATE_NEW_TRIP_MAIN_TEXT: "Can't create this trip You have exceeded 10 trips.",
        ERROR_CREATE_NEW_TRIP_MINOR_TEXT: 'If you want to create more trips Able to delete unwanted trips',
        // validate,
        PLEASE_SELECT_TEXT: 'Please select province',
        PLEASE_ENTER_TEXT: 'Please enter trip name',
    },
}
