/// <reference types="react-scripts" />

enum EnumResourceType {
    AlertLevel = 1,
    AlertParkingType = 2,
    AlertType = 3,
    AreaParkingType = 5,
    AreaUnit = 6,
    AuditTrailActionType = 7,
    AuditTrailEntityType = 8,
    AuthenticationType = 9,
    BoxFeatureEventType = 10,
    BoxStatus = 11,
    ContractType = 12,
    Currency = 13,
    CustomAreaType = 14,
    DirectionType = 15,
    DistanceUnit = 16,
    DriveGrade = 17,
    DriverCardType = 18,
    DriverLicenseType = 19,
    DrivingType = 20,
    EnumResourceType = 21,
    EventActionType = 22,
    EventDataType = 23,
    EventType = 24,
    FeatureUnit = 25,
    FileType = 26,
    Gender = 27,
    GpsStatus = 28,
    GsmStatus = 29,
    JobStatus = 30,
    JobWaypointStatus = 31,
    LoginActionType = 32,
    MaintenanceStatus = 33,
    MediaEntityType = 35,
    MediaFieldName = 36,
    MovementType = 37,
    NotificationAction = 38,
    NotificationStatus = 39,
    NotificationType = 40,
    PaymentType = 41,
    PermissionCategory = 42,
    PlaybackDisplayType = 43,
    PlaybackTrackingType = 44,
    PoiCheckInType = 45,
    Portal = 46,
    ReportTemplateSection = 47,
    ReportTemplateType = 48,
    ResourceType = 49,
    RouteMode = 50,
    RouteOption = 51,
    RouteOptionDescription = 52,
    SearchEntityType = 53,
    StopChange = 54,
    TaskLogStatus = 55,
    TemperatureUnit = 56,
    TrackableType = 57,
    TrackVehicleIconType = 58,
    UserPreferenceKey = 59,
    VehicleRegisteredType = 60,
    VehicleType = 61,
    VolumeUnit = 62,
    WeightUnit = 63,
    ReportFieldDataType = 64,
    PortalMode = 65,
    GpsChange = 66,
    DltStatus = 67,
    GlobalSearchLogisticsCategory = 68,
    LocationReferenceType = 69,
    GlobalSearchType = 70,
    TimeUnit = 71,
    ParkingType = 72,
    GeneralReportType = 73,
    DrivingReportType = 74,
    ComparisonReportType = 75,
    SummaryReportType = 76,
    DelinquentReportType = 77,
    BackwardDurationType = 78,
    AppointmentStatus = 79,
    VehicleMaintenanceType = 80,
    FuelType = 81,
    EngineType = 82,
    GroupByType = 83,
    MaintenanceReportType = 84,
    TicketStatus = 85,
    TicketAppointmentStatus = 86,
    TicketDuration = 88,
    SimStatus = 89,
    CategoryType = 90,
    ERMVehicleType = 91,
    DeliveryType = 92,
    AccessType = 93,
    ManeuverLevel = 95,
    DeliveryOrderStatus = 96,
    AlertTicketStatus = 97,
    JobAutoFinish = 98,
    LateShipmentRole = 99,
    PoiCategoryType = 100,
    ParkingUtilizationType = 101,
    MovingUtilizationType = 102,
    MDVRModel = 103,
    JobTimelineTruckStatus = 104,
    JobTimelineSort = 105,
    GISServiceClassType = 106,
    GISServiceType = 107,
    AlertUnauthorizedCondition = 108,
    AlertUnauthorizedConfigType = 109,
    AlertUnauthorizedSpeedType = 110,
    Day = 111,
    AreaCategoryType = 112,
    JobArrivalType = 113,
    TravelMode = 114,
    PermissionType = 115,
    PoiType = 116,
    IntegrationType = 117,
    ManeuverLevelFilter = 118,
    TurnOption = 119,
    AutomailReportCategory = 120,
    ScheduleFrequency = 121,
    TripAnalysisReport = 122,
    AlertSound = 123,
    ConnectorFormat = 124,
    DltManagementMainStatus = 125,
    DltManagementSubStatus = 126,
    DltManagementType = 127,
    DltReportType = 128,
    POSState = 129,
    PetrolType = 130,
    OrderType = 131,
    ExpenseType = 132,
    LineKeyType = 133,
    PODStepDataType = 134,
    SaleRequestStatus = 135,
    SaleType = 136,
    SaleRequestSource = 137,
    SaleRequestUserType = 138,
    TaskStatus = 139,
    TaskType = 140,
    ContactType = 141,
    JobDeliveryManStatus = 142,
    SaleRequestFileType = 143,
    AccidentDirection = 144,
    SaleInstallationStatus = 145,
    SaleDevicePosition = 146,
}

enum AuthenticationType {
    Form = 1,
    ActiveDirectory = 2,
    PEAIdm = 3,
}

enum InfoStatus {
    Original = 1,
    Add = 2,
    Update = 3,
    Delete = 4,
}

enum UserPreferenceKey {
    DefaultVehicleIconType = 1,
    EnableSoundAlert,
    FleetDelayTime,
    Dashboard,
    Bookmark,
    PreferredLanguage,
    AssetIdsForFleetMonitoring,
    DataGridState,
    AlertNotification,
    FavoriteMenuWorkSpace,
    FavoriteMenuBackOffice,
}
